name: CD with Gradle and Docker

on:
  push:
    branches:
      - 'develop'
      - 'main'
  pull_request:
    branches:
      - 'develop'
      - 'main'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: ☕️ set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: 👏🏻 grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 🐘 build with Gradle (without test)
        run: ./gradlew clean build -x test --stacktrace

      - name: 🐳 Docker build & push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}

      - name: 🚀 deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            ENV_FILE='/etc/idus-server/.env'
            IMAGE="${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}"
            CONTAINER_NAME="${{ secrets.CONTAINER_NAME }}"

            echo "===== SERVER INFO ====="
            hostname
            echo "IMAGE: [$IMAGE]"
            echo "CONTAINER: [$CONTAINER_NAME]"
            echo "ENV_FILE: [$ENV_FILE]"
            echo "======================="

            echo "✋🏻Stopping existing container"
            sudo docker stop "$CONTAINER_NAME" || true
            sudo docker rm "$CONTAINER_NAME" || true

            echo "🥳 Pulling new image"
            sudo docker pull "$IMAGE"

            echo "🌱 Running new container"
            sudo docker run -d \
              -p 8080:8080 \
              --name "$CONTAINER_NAME" \
              --env-file "$ENV_FILE" \
              "$IMAGE"

            echo "🧾 Current containers"
            sudo docker ps -a

            echo "🚮 Cleaning up old images"
            sudo docker image prune -f
